a_set = set([1,2,3,4,5])
b_set = set([3,4,5,6,7,8,9])

print('Union')
print(a_set | b_set)
print('Difference')
print(a_set - b_set)
print('Intersection')
print(a_set & b_set)
print('Exclusive')
print(a_set ^ b_set)
